### ISSUE TITLE
[Feature]: เพิ่ม Link Opensea ใน Landing page

### ISSUE THREAD

**Issue by mrthiti** [Naga-DAO/naga-mint-workspace#16]
### Description?

เพิ่ม Link Opensea ใน Landing page ในตําแหน่งนี้ครับ

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/7018802/168750985-3aaaa373-d9b3-42d6-80da-f2fd8e94e661.png">

และใน Footer ด้วยครับ

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/7018802/168775083-ce21274f-345f-424d-a3c5-0ee26894bba0.png">

**Comment by PattoMotto** [comment]
working on it 🙈
